// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/covergates/covergates/core (interfaces: BuildStore,BuildService)

package mock

import (
	context "context"
	reflect "reflect"

	core "github.com/covergates/covergates/core"
	gomock "github.com/golang/mock/gomock"
)

// MockBuildStore is a mock of BuildStore interface.
type MockBuildStore struct {
	ctrl     *gomock.Controller
	recorder *MockBuildStoreMockRecorder
}

// MockBuildStoreMockRecorder is the mock recorder for MockBuildStore.
type MockBuildStoreMockRecorder struct {
	mock *MockBuildStore
}

// NewMockBuildStore creates a new mock instance.
func NewMockBuildStore(ctrl *gomock.Controller) *MockBuildStore {
	mock := &MockBuildStore{ctrl: ctrl}
	mock.recorder = &MockBuildStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildStore) EXPECT() *MockBuildStoreMockRecorder {
	return m.recorder
}

// AddJob mocks base method.
func (m *MockBuildStore) AddJob(build *core.Build, job *core.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddJob", build, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddJob indicates an expected call of AddJob.
func (mr *MockBuildStoreMockRecorder) AddJob(build, job interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddJob", reflect.TypeOf((*MockBuildStore)(nil).AddJob), build, job)
}

// Create mocks base method.
func (m *MockBuildStore) Create(build *core.Build) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", build)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBuildStoreMockRecorder) Create(build interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBuildStore)(nil).Create), build)
}

// FindByCommit mocks base method.
func (m *MockBuildStore) FindByCommit(repoID uint, commit string) (*core.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCommit", repoID, commit)
	ret0, _ := ret[0].(*core.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCommit indicates an expected call of FindByCommit.
func (mr *MockBuildStoreMockRecorder) FindByCommit(repoID, commit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCommit", reflect.TypeOf((*MockBuildStore)(nil).FindByCommit), repoID, commit)
}

// FindByNumber mocks base method.
func (m *MockBuildStore) FindByNumber(repoID uint, number int) (*core.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNumber", repoID, number)
	ret0, _ := ret[0].(*core.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNumber indicates an expected call of FindByNumber.
func (mr *MockBuildStoreMockRecorder) FindByNumber(repoID, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNumber", reflect.TypeOf((*MockBuildStore)(nil).FindByNumber), repoID, number)
}

// FindByServiceNumber mocks base method.
func (m *MockBuildStore) FindByServiceNumber(repoID uint, serviceNumber string) (*core.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByServiceNumber", repoID, serviceNumber)
	ret0, _ := ret[0].(*core.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByServiceNumber indicates an expected call of FindByServiceNumber.
func (mr *MockBuildStoreMockRecorder) FindByServiceNumber(repoID, serviceNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByServiceNumber", reflect.TypeOf((*MockBuildStore)(nil).FindByServiceNumber), repoID, serviceNumber)
}

// Jobs mocks base method.
func (m *MockBuildStore) Jobs(buildID uint) ([]*core.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Jobs", buildID)
	ret0, _ := ret[0].([]*core.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Jobs indicates an expected call of Jobs.
func (mr *MockBuildStoreMockRecorder) Jobs(buildID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Jobs", reflect.TypeOf((*MockBuildStore)(nil).Jobs), buildID)
}

// LatestOnBranch mocks base method.
func (m *MockBuildStore) LatestOnBranch(repoID uint, branch string, excludeBuildID uint) (*core.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestOnBranch", repoID, branch, excludeBuildID)
	ret0, _ := ret[0].(*core.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestOnBranch indicates an expected call of LatestOnBranch.
func (mr *MockBuildStoreMockRecorder) LatestOnBranch(repoID, branch, excludeBuildID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestOnBranch", reflect.TypeOf((*MockBuildStore)(nil).LatestOnBranch), repoID, branch, excludeBuildID)
}

// List mocks base method.
func (m *MockBuildStore) List(repoID uint, branch string, limit, offset int) ([]*core.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", repoID, branch, limit, offset)
	ret0, _ := ret[0].([]*core.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBuildStoreMockRecorder) List(repoID, branch, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBuildStore)(nil).List), repoID, branch, limit, offset)
}

// Update mocks base method.
func (m *MockBuildStore) Update(build *core.Build) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", build)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBuildStoreMockRecorder) Update(build interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBuildStore)(nil).Update), build)
}

// MockBuildService is a mock of BuildService interface.
type MockBuildService struct {
	ctrl     *gomock.Controller
	recorder *MockBuildServiceMockRecorder
}

// MockBuildServiceMockRecorder is the mock recorder for MockBuildService.
type MockBuildServiceMockRecorder struct {
	mock *MockBuildService
}

// NewMockBuildService creates a new mock instance.
func NewMockBuildService(ctrl *gomock.Controller) *MockBuildService {
	mock := &MockBuildService{ctrl: ctrl}
	mock.recorder = &MockBuildServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildService) EXPECT() *MockBuildServiceMockRecorder {
	return m.recorder
}

// Finalize mocks base method.
func (m *MockBuildService) Finalize(ctx context.Context, repo *core.Repo, build *core.Build) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finalize", ctx, repo, build)
	ret0, _ := ret[0].(error)
	return ret0
}

// Finalize indicates an expected call of Finalize.
func (mr *MockBuildServiceMockRecorder) Finalize(ctx, repo, build interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockBuildService)(nil).Finalize), ctx, repo, build)
}
